apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: products
          ports:
            - containerPort: 8002
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
