apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping
          image: shopping
          ports:
            - containerPort: 8003
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
