name: Deploy on QA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy_on_qa:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      
      - name: Create customer Env file
        working-directory: ./customer
        run: |
          touch .env
          echo APP_SECRET=sd >> .env
          echo MONGODB_URI=mongodb://nosql-db:27017/shop-ms-customers >> .env
          echo MSG_QUEUE_URL=amqps://typssqfb:Q0N4kQNImWJ9-ku8wCYFzlYQPI8NMzwT@lionfish.rmq.cloudamqp.com/typssqfb >> .env
          echo EXCHANGE_NAME=ONLINE_STORE >> .env
          echo PORT=8001 >> .env
          cat .env

      - name: Create Products Env file
        working-directory: ./products
        run: |
          touch .env
          echo APP_SECRET=sd >> .env
          echo MONGODB_URI=mongodb://nosql-db:27017/shop-ms-products >> .env
          echo MSG_QUEUE_URL=amqps://typssqfb:Q0N4kQNImWJ9-ku8wCYFzlYQPI8NMzwT@lionfish.rmq.cloudamqp.com/typssqfb >> .env
          echo EXCHANGE_NAME=ONLINE_STORE >> .env
          echo PORT=8002 >> .env
          cat .env
          
      - name: Create shopping Env file
        working-directory: ./shopping
        run: |
          touch .env
          echo APP_SECRET=sd >> .env
          echo MONGODB_URI=mongodb://nosql-db:27017/shop-ms-shopping >> .env
          echo MSG_QUEUE_URL=amqps://typssqfb:Q0N4kQNImWJ9-ku8wCYFzlYQPI8NMzwT@lionfish.rmq.cloudamqp.com/typssqfb >> .env
          echo EXCHANGE_NAME=ONLINE_STORE >> .env
          echo PORT=8003 >> .env
          cat .env
          
      - name: Generate deployment package
        run: |
          zip -r deploy.zip . -x '*.git'
      
      - name: Deploy on Elastic beanstalk QA Env
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: sd-qa-node-app
          environment_name: Sd-qa-node-app-env
          version_label: 1.0
          region: ap-south-1
          deployment_package: deploy.zip

      
        
