name: Continuous Integration

on:
  pull_request:
    branches: ["main"]

jobs:
  ci_verification:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test Customer Service
        working-directory: ./customer
        run: |
          npm ci
          npm test
      - name: Test Products Service
        working-directory: ./products
        run: |
          npm ci
          npm test
      - name: Test Shopping Service
        working-directory: ./shopping
        run: |
          npm ci
          npm test
