name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ci-verification:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Test Customer Service
      working-directory: ./customer
      run: |
        npm ci
        npm test
